language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: JexUh6nSTa9/bllzrD2MNzhSlHyz880CNrT2tli7eD9jhcJ0R05D1+aJrVYamAR0IdZI1RpYUL4cP4kRx3ibwqRxUWAKCHY8wb0uhA9886LYvZjCRQadgNDL/c8X5YEXitfs2IWmUGK6MkPnXyr3MW3fzFpZ6z51yp3QlFaV/a3PpR/e0/kPpOUxwr38F74OvYJz4E61JJ5Ki4h8YvGxOSD6d2yv5M/dO5pttxp4dl0TTWcz1dYQhSmr37QB44Ipl5bpXdVeR4FMtTdDhyc7VGJDImAm2zaIYEjGKtqpG5987YVx7v8DDL2yk52m2vANQJABP7ZlVrte0ORHUq6SYJ2bgM8qn3L1r1Fmu/HsH6lEWnKZkmCRcBusa84OrPoM/KG9ytdePs+TvKGKKu0bOzOoE4iDH+S+6L2J1mf0vn/GTl/wdFFDPukkCI2wI3+t9Bgd1QdsHGF9YnCjxNMUwJgVEPThRyhZhAsAPTUoEGO9mNcfTOxuE+vjk1TdvhNO+DYXdPZk+DQUNcuwwWiGvo5A3FR38J/q2QsiSVrotC5omWNOHZfIiRy5BzdG91/AKVUjmA0BCoSIa78WChscFkXw+IxQ3emCeM8D/45QRqCFJGzA/lRV1rYMjVlT/odzjoh3MnxCFUqSS3YcDxC+EaoyOLKvqHF1EqV0nyhwL8o=
